"""add_wb_data_models

Revision ID: 647af18b4019
Revises: e2996d9fd119
Create Date: 2026-04-09 10:17:55.688805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647af18b4019'
down_revision: Union[str, None] = 'e2996d9fd119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('synced_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_organization_id'), 'sync_logs', ['organization_id'], unique=False)
    op.create_table('wb_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('g_number', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('tech_size', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('warehouse_name', sa.String(length=200), nullable=True),
    sa.Column('region_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('is_supply', sa.String(length=10), nullable=True),
    sa.Column('is_storno', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_orders_date'), 'wb_orders', ['date'], unique=False)
    op.create_index(op.f('ix_wb_orders_g_number'), 'wb_orders', ['g_number'], unique=False)
    op.create_index(op.f('ix_wb_orders_nm_id'), 'wb_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_orders_order_id'), 'wb_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_wb_orders_organization_id'), 'wb_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wb_orders_status'), 'wb_orders', ['status'], unique=False)
    op.create_table('wb_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('sizes', sa.JSON(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_products_nm_id'), 'wb_products', ['nm_id'], unique=True)
    op.create_index(op.f('ix_wb_products_organization_id'), 'wb_products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wb_products_vendor_code'), 'wb_products', ['vendor_code'], unique=False)
    op.create_table('wb_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.String(length=100), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reward', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('g_number', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('tech_size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_with_disc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('region_name', sa.String(length=200), nullable=True),
    sa.Column('warehouse_name', sa.String(length=200), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('supplier_oper_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_sales_date_from'), 'wb_sales', ['date_from'], unique=False)
    op.create_index(op.f('ix_wb_sales_date_to'), 'wb_sales', ['date_to'], unique=False)
    op.create_index(op.f('ix_wb_sales_nm_id'), 'wb_sales', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_organization_id'), 'wb_sales', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_sale_id'), 'wb_sales', ['sale_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_sales_sale_id'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_organization_id'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_nm_id'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_date_to'), table_name='wb_sales')
    op.drop_index(op.f('ix_wb_sales_date_from'), table_name='wb_sales')
    op.drop_table('wb_sales')
    op.drop_index(op.f('ix_wb_products_vendor_code'), table_name='wb_products')
    op.drop_index(op.f('ix_wb_products_organization_id'), table_name='wb_products')
    op.drop_index(op.f('ix_wb_products_nm_id'), table_name='wb_products')
    op.drop_table('wb_products')
    op.drop_index(op.f('ix_wb_orders_status'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_organization_id'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_order_id'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_nm_id'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_g_number'), table_name='wb_orders')
    op.drop_index(op.f('ix_wb_orders_date'), table_name='wb_orders')
    op.drop_table('wb_orders')
    op.drop_index(op.f('ix_sync_logs_organization_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
