"""Add need_kiz, kiz_marked, photo_url to wb_products

Revision ID: 878bbd306692
Revises: 647af18b4019
Create Date: 2026-04-10 09:32:42.200960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878bbd306692'
down_revision: Union[str, None] = '647af18b4019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_products', sa.Column('need_kiz', sa.Boolean(), nullable=True))
    op.add_column('wb_products', sa.Column('kiz_marked', sa.Boolean(), nullable=True))
    op.add_column('wb_products', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wb_products', 'photo_url')
    op.drop_column('wb_products', 'kiz_marked')
    op.drop_column('wb_products', 'need_kiz')
    # ### end Alembic commands ###
