"""add_wb_keyword_seasonality

Revision ID: f1e2d3c4b5a6
Revises: x0y1z2a3b4c5
Create Date: 2026-07-08 17:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e2d3c4b5a6'
down_revision: Union[str, None] = 'x0y1z2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_keyword_seasonality',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('normquery', sa.String(length=500), nullable=True),
    sa.Column('freq365', sa.Integer(), nullable=True),
    sa.Column('freq_monthly', sa.Integer(), nullable=True),
    sa.Column('freq_weekly', sa.Integer(), nullable=True),
    sa.Column('weekly_trend', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('wb_subject_id', sa.Integer(), nullable=True),
    sa.Column('wb_subject_name', sa.String(length=200), nullable=True),
    sa.Column('freq_history_monthly', postgresql.JSONB(), nullable=True),
    sa.Column('freq_history_weekly', postgresql.JSONB(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True, server_default='evirma'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_keyword_seasonality_keyword'), 'wb_keyword_seasonality', ['keyword'], unique=False)
    op.create_index(op.f('ix_wb_keyword_seasonality_organization_id'), 'wb_keyword_seasonality', ['organization_id'], unique=False)
    op.create_index('uq_wb_keyword_seasonality_keyword_source_collected', 'wb_keyword_seasonality', ['keyword', 'source', 'collected_at'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_wb_keyword_seasonality_keyword_source_collected', table_name='wb_keyword_seasonality')
    op.drop_index(op.f('ix_wb_keyword_seasonality_organization_id'), table_name='wb_keyword_seasonality')
    op.drop_index(op.f('ix_wb_keyword_seasonality_keyword'), table_name='wb_keyword_seasonality')
    op.drop_table('wb_keyword_seasonality')
    # ### end Alembic commands ###
